sudo: required
language: bash
services: docker
env:
  matrix:
  - ARCH=x86_64 PUID=1000 PGID=1000
  - ARCH=armhf PUID=1001 PGID=1001
  global:
  - secure: wpJYSaXUIEdqUxjFevv56ENLhhEuq9heL0ZpoPTnVallmJ4r4HN2idS+frqNM7wZYfBBGiufdvwdPvzKOEk65eDI3Rw2X6YZgX50tSt2E3a/NW/JWu5ubLLzuBYrIguGmGAdvR/AyOGqH1C/cVi9jiDl+TVlmSriVfufhUMZOoYsBtX+j0/F8bLCQxiu6+rVjTvRlVi3hz97kwyZm6kdm80lWpFDy1A2J/XzaK5w+iaN/SI5BnQW6H4czVMZn0Z1VpFBpJOgcCQYL01580/vicXuZKx2e4Xum3xu0YgjKtrMOdloMsEVGr/Q3EZ0IRx7YtUkuY0YVEkbTqspEpFJTI/cuX6pMDnFq7hlLMhK0xxkRbvPQz0nM2F4Uocu8qMyjMMxhMCAuvcfI9cm0HLBnFZAruOTukqCIkj+fJqpFLHACDnGOqqIZfqSXH7cUDEExloFjvd3J71KEEP3tx3mejcaicZcFt1MdeXzD3we3VbplXxbqrcqxa8RJlchWL65YNH8XUgaf8DCuoWjUdSF7V75MPLmWF/HxT1DEHiW9dW86jzhLz6FTYu/dW5Ov6B56tkA9BkRlDrdmjethahbOtf9/2XLVaqyeMFQ+0GkhTGSK1GefWblygvYsN1sjsbGWqRsTnOvkSIh4rXMKOUPPScIHP/QuvI7giYapqMOFgI=
  - secure: YxBxZkzkpTokq63/wu9nLdF+u7NxgVTGRdw0LxznXNHdbZk3R/zdg0VF4nhU1yHEcVKhjbadfY1xQCqv/OZ6UBJqje3zY5qEwqO6zYI2oIukB/sTkxcnJBXxo9G55GZJsLWQD1idOAj8l8x7hZwMn9TsAJwbwr7Ay8YLI8n4WBAQIQcC37CUeWikIAnpHp0P0BuPcQo5pH+G3Ufa09uX3TMVhIwJAbx8EhbFD+rp4dQ2u/NVT6z+Ttts5exglVA34waJYhCqXAfQfC1nZb58l2B9/0d7CTteEGfR7NPlAnnvK2eBWEBD5lLio7CRAnZ6RehpkHIyOr8eD+X7Qf0iH01aoEkcRPj9ifaDnWtbP2amqff1lD/BswJF8HA0i45lQNhkrRx1A+eyNy38CjzaXNzpNDilzY+9ntI44N7SQsdaic2Qum0WpqQhM3Fjn3ZeccIprl4X3CUGT7DDnuTNJJVAgy7upKpwK/wI5dGzQvXYtPWKCiCHukt3VCZoq9JP5W2vUYfMZHfC/iDPEfmY/bKH4i/OOD6iiptK8ht+zbdvWQXHA5Zj2x0RS1T/bHKmkq/q+JO18KUBPlGytG/quCbceAvpHVQemL1rB9Tx/u1tT9VI3ogg6XY8pnI194HehV+neNAjbjP2EzjNZzVvuGjnIGZu+Sa89Nhz/Q5jrFE=
install: true
before_script:
- docker --version
- make --version
script:
- make ARCH=${ARCH} PUID=${PUID} PGID=${PGID} build test
after_success:
- docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
- make ARCH=${ARCH} push
after_script:
- docker logout
- make clean
